name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: "sqp_2b1ed6a0793eb286aa6e2c2adfd64afc24816df9"
          SONAR_HOST_URL: "https://16e4-182-70-121-2.in.ngrok.io"
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
       - uses: sonarsource/sonarqube-quality-gate-action@master
         timeout-minutes: 5
         env:
           SONAR_TOKEN: "sqp_2b1ed6a0793eb286aa6e2c2adfd64afc24816df9"