name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
      - development # or the name of your main branch
      - nandeep # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: sqp_a4e1c564ea212348fbbf9a5c767468d8993826ce
      #     SONAR_HOST_URL: https://sonarqube.openxcell.dev
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # We do not recommend to use this in a pull request. Prefer using pull request
      # decoration instead.
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: sqp_a4e1c564ea212348fbbf9a5c767468d8993826ce
          SONAR_HOST_URL: https://sonarqube.openxcell.dev